/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateBenefitArgs } from "./CreateBenefitArgs";
import { UpdateBenefitArgs } from "./UpdateBenefitArgs";
import { DeleteBenefitArgs } from "./DeleteBenefitArgs";
import { BenefitFindManyArgs } from "./BenefitFindManyArgs";
import { BenefitFindUniqueArgs } from "./BenefitFindUniqueArgs";
import { Benefit } from "./Benefit";
import { PurchaseFindManyArgs } from "../../purchase/base/PurchaseFindManyArgs";
import { Purchase } from "../../purchase/base/Purchase";
import { BenefitService } from "../benefit.service";

@graphql.Resolver(() => Benefit)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class BenefitResolverBase {
  constructor(
    protected readonly service: BenefitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "any",
  })
  async _benefitsMeta(
    @graphql.Args() args: BenefitFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Benefit])
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "any",
  })
  async benefits(
    @graphql.Args() args: BenefitFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Benefit[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Benefit",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Benefit, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "own",
  })
  async benefit(
    @graphql.Args() args: BenefitFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Benefit | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Benefit",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Benefit)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "create",
    possession: "any",
  })
  async createBenefit(
    @graphql.Args() args: CreateBenefitArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Benefit> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Benefit",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Benefit"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Benefit)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "update",
    possession: "any",
  })
  async updateBenefit(
    @graphql.Args() args: UpdateBenefitArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Benefit | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Benefit",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Benefit"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Benefit)
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "delete",
    possession: "any",
  })
  async deleteBenefit(
    @graphql.Args() args: DeleteBenefitArgs
  ): Promise<Benefit | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Purchase])
  @nestAccessControl.UseRoles({
    resource: "Benefit",
    action: "read",
    possession: "any",
  })
  async purchases(
    @graphql.Parent() parent: Benefit,
    @graphql.Args() args: PurchaseFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Purchase[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Purchase",
    });
    const results = await this.service.findPurchases(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
