/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BenefitWhereInput } from "./BenefitWhereInput";
import { Type } from "class-transformer";
import { BenefitOrderByInput } from "./BenefitOrderByInput";

@ArgsType()
class BenefitFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => BenefitWhereInput,
  })
  @Field(() => BenefitWhereInput, { nullable: true })
  @Type(() => BenefitWhereInput)
  where?: BenefitWhereInput;

  @ApiProperty({
    required: false,
    type: BenefitOrderByInput,
  })
  @Field(() => BenefitOrderByInput, { nullable: true })
  @Type(() => BenefitOrderByInput)
  orderBy?: BenefitOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { BenefitFindManyArgs };
