/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePurchaseArgs } from "./CreatePurchaseArgs";
import { UpdatePurchaseArgs } from "./UpdatePurchaseArgs";
import { DeletePurchaseArgs } from "./DeletePurchaseArgs";
import { PurchaseFindManyArgs } from "./PurchaseFindManyArgs";
import { PurchaseFindUniqueArgs } from "./PurchaseFindUniqueArgs";
import { Purchase } from "./Purchase";
import { Benefit } from "../../benefit/base/Benefit";
import { Customer } from "../../customer/base/Customer";
import { PurchaseService } from "../purchase.service";

@graphql.Resolver(() => Purchase)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PurchaseResolverBase {
  constructor(
    protected readonly service: PurchaseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "read",
    possession: "any",
  })
  async _purchasesMeta(
    @graphql.Args() args: PurchaseFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Purchase])
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "read",
    possession: "any",
  })
  async purchases(
    @graphql.Args() args: PurchaseFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Purchase[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Purchase",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Purchase, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "read",
    possession: "own",
  })
  async purchase(
    @graphql.Args() args: PurchaseFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Purchase | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Purchase",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Purchase)
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "create",
    possession: "any",
  })
  async createPurchase(
    @graphql.Args() args: CreatePurchaseArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Purchase> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Purchase",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Purchase"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        benefit: {
          connect: args.data.benefit,
        },

        customer: {
          connect: args.data.customer,
        },
      },
    });
  }

  @graphql.Mutation(() => Purchase)
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "update",
    possession: "any",
  })
  async updatePurchase(
    @graphql.Args() args: UpdatePurchaseArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Purchase | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Purchase",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Purchase"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          benefit: {
            connect: args.data.benefit,
          },

          customer: {
            connect: args.data.customer,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Purchase)
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "delete",
    possession: "any",
  })
  async deletePurchase(
    @graphql.Args() args: DeletePurchaseArgs
  ): Promise<Purchase | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Benefit, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "read",
    possession: "any",
  })
  async benefit(
    @graphql.Parent() parent: Purchase,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Benefit | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Benefit",
    });
    const result = await this.service.getBenefit(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Customer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Purchase",
    action: "read",
    possession: "any",
  })
  async customer(
    @graphql.Parent() parent: Purchase,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Customer | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Customer",
    });
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
