/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ScoreWhereUniqueInput } from "./ScoreWhereUniqueInput";
import { ScoreUpdateInput } from "./ScoreUpdateInput";

@ArgsType()
class UpdateScoreArgs {
  @Field(() => ScoreWhereUniqueInput, { nullable: false })
  where!: ScoreWhereUniqueInput;
  @Field(() => ScoreUpdateInput, { nullable: false })
  data!: ScoreUpdateInput;
}

export { UpdateScoreArgs };
